name: API Teste Regressivos Agendado Robot API

on:
  pull_request:
    branches: [ main ]
  Scheudule:
     - cron:  '*/60 10 * * 1-5'

jobs:
  RunApiTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Especifique a versão desejada do Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests

      - name: Run Robot Framework tests
        run: |
          robot -d ./log -i Regressivo TestCasesAPIBooks.robot

      - name: Generate Allure report
        run: |
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.14.0/allure-commandline-2.14.0.zip
          unzip allure-commandline-2.14.0.zip -d /opt
          sudo ln -s /opt/allure-2.14.0/bin/allure /usr/bin/allure
          allure generate ./log -o ./allure-report

      - name: Verify Allure report generation
        run: |
          ls -l ./allure-report

      - name: Archive Allure report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

      - name: Archive Robot Framework report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: robot-framework-report
          path: ./log
